version: '3.8'

services:
  k6:
    image: grafana/k6:0.49.0
    environment:
      - BASE_URL=${BASE_URL:-http://host.docker.internal:5000}
      - API_KEY=${API_KEY:-}
      - CLIENT_ID=${CLIENT_ID:-client_acme_corp}
      - VUS=${VUS:-10}
      - DURATION=${DURATION:-1m}
    volumes:
      - ./loadtest/k6:/scripts
      - ./loadtest/results:/results
    command: ["run", "--summary-export=/results/summary.json", "/scripts/survey-load.js"]
    # network not required if using host.docker.internal
    # depends_on can be added if combining with main compose
